### PR TITLE
bro put analyst on role name, but forgot to but analyst on info and infolong 💀 

### PR DESCRIPTION
**Pull request by PHGaming121**
bro put analyst on role name, but forgot to but analyst on info and infolong 💀

### CODE REVIEW

**Comment by PHGaming121** [comment]
wait a minute..

**BRO ALSO FORGOT TO CHANGE SOME CustomRoles.Analyzer to CustomRoles.Analyst**

**Comment by PHGaming121** [comment]
> wait a minute..
> 
> **BRO ALSO FORGOT TO CHANGE SOME CustomRoles.Analyzer to CustomRoles.Analyst**

forget about this, i guess it was an error on my side ._.

**Comment by PHGaming121** [comment]
> > wait a minute..
> > **BRO ALSO FORGOT TO CHANGE SOME CustomRoles.Analyzer to CustomRoles.Analyst**
> 
> forget about this, i guess it was an error on my side ._.

it **WAS** an error on my side: 10 roles got the same UsePet setting that Analyst uses 💀

**Review by Gurge44 — APPROVED** [review]

**Comment by Gurge44** [comment]
CTRL + SHIFT + H

**Pull request merged**
