### PR TITLE
Update en_US.json

### PR DESCRIPTION
**Pull request by KingPanda360**
Just some wording updates

### CODE REVIEW

**Comment by Ultradragon005** [comment]
oh god, broski wants to correct the Overlord of correcting spelling mistakes 💀🗿

**Comment by KingPanda360** [comment]
> oh god, broski wants to correct the Overlord of correcting spelling mistakes 💀🗿

I knew that was coming. So predictable.

**Comment by HyperAtill** [comment]
By the way, Amnesiac's info should be "Copy someone's role", since now in settings host can make Amnesiac copy via report button

**Comment by KingPanda360** [comment]
> By the way, Amnesiac's info should be "Copy someone's role", since now in settings host can make Amnesiac copy via report button

Done

**Comment by HyperAtill** [comment]
> > By the way, Amnesiac's info should be "Copy someone's role", since now in settings host can make Amnesiac copy via report button
> 
> Done

Nice! Thanks!

**Pull request merged**
