### PR TITLE
Modify and apply COOL animations in Main Menu

### PR DESCRIPTION
**Pull request by PHGaming121**
Credits for code: TONX and MoreGamemodes

### CODE REVIEW

**Comment by PHGaming121** [comment]
converted to draft for NOT IMMEDIATELY merge, because i need to see if gurge (and also the community) approves the changes

**Comment by PHGaming121** [comment]
sorry, cant upload video here because size ._.

**Comment by Gurge44** [comment]
So, what are we waiting for?

**Comment by PHGaming121** [comment]
> So, what are we waiting for?

alright, u can merge :)

**Comment by PHGaming121** [comment]
wait
i will make my final suggestion: credits button sends us to github

**Comment by PHGaming121** [comment]
> wait i will make my final suggestion: credits button sends us to EHR Website (instead of Github?)

idk lol

**Comment by PHGaming121** [comment]
i somehow found out how to fix credits screen not closing 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀

**Comment by PHGaming121** [comment]
alright, now u  can merge

**Comment by PHGaming121** [comment]
no website button :(

**Comment by PHGaming121** [comment]
what i did was rewrite the code for update button, for it to use the same code as the other 3 buttons, since I THINK this was causing a nullreference on the menu start

**Comment by PHGaming121** [comment]
i swear if there are more things to do, im dying

**Pull request merged**
