### PR TITLE
Completely Fix Cno For modded client

### PR DESCRIPTION
**Pull request by Ultradragon005**
ignore the other stuff for now I remove later. I just needed those to be able and play.

### CODE REVIEW

**Comment by Ultradragon005** [comment]
Why dosen't the customrpc work 😭

**Comment by Ultradragon005** [comment]
oh wait I was looking at host logs to try finding the modded client recieverpc 💀

**Comment by Ultradragon005** [comment]
image
BRUHHHHHHHHHHHH, holy shit, now time to figure out how I find a thing which can have a number

**Comment by Ultradragon005** [comment]
but it's working for host now without the txttmp

**Comment by Ultradragon005** [comment]
I'll jsut do a foreach loop and try all of them 😂😂

**Comment by Gurge44** [comment]
For now I just made RPCs for non-host modded clients to sync the text tmp, I'm writing the release notes lol

**Comment by Ultradragon005** [comment]
image
sob. Somehow it does not let me set it active for modded client after it has been recieved trough an rpc. I'll try object.find("") maybe that will help somehow 💀

**Comment by Ultradragon005** [comment]
image
image
image

Welp, I'll let tomorrow me try to figure this shit out.

**Comment by Ultradragon005** [comment]
fixed it for modded client by just adding a delay bruh 💀

**Comment by Dxgamer7405** [comment]
> fixed it for modded client by just adding a delay bruh 💀

try check why commands doesnt work for non host modded clients

**Comment by Gurge44** [comment]
lol you could've just used Utils.SendRPC for the custom rpcs

**Comment by Ultradragon005** [comment]
ngl, autorpc came after messing around when the real problem was that it had to be delayed. and then I just didn't bother anymore lol, but Ig I can do it now

**Comment by Gurge44** [comment]
lol I meant you could look at Utils.SendRPC and its usages just to find out how easier rpc sending is with it

**Pull request merged**
