### PR TITLE
ADD NEW ROLE: thewhiskas27 ULTIMATUS (Super op)

### PR DESCRIPTION
**Pull request by Ultradragon005**

### CODE REVIEW

**Comment by Ultradragon005** [comment]
wait nvm this is too op

**Comment by Gurge44** [comment]
how dare you do that for the 100th pr

**Comment by Ultradragon005** [comment]
OH LMFAOOO I didn't even realize

**Comment by Ultradragon005** [comment]
I guess it was jsut soo op it even grapped the 100#th spot 😼

**Comment by Tommy-XL** [comment]
Lol

**Pull request closed without merging**
